import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class Contacts_Wallet(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'Contacts&Wallet'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testContacts_Wallet(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Creating New Contact from Reservation\")")
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']  ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='newContactAdd'] | //*[@id='newContactAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName'] ").send_keys('Prajwal')
        self.driver.find_element_by_xpath("//*[@content-desc='mobileCont'] | //*[@id='mobileCont'] ").send_keys('8937773734')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveContact'] | //*[@id='saveContact'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Prajwal')
        self.driver.hide_keyboard()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='back'] | //*[@id='back']")))
        self.driver.find_element_by_xpath("//*[@content-desc='back'] | //*[@id='back'] ").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.execute_script("seetest:client.sendText(\" 2. Adding Guest from Wallet after Creating an Event\")")
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']")))
        // self.driver.find_element_by_xpath("//*[@content-desc='Invite'] | //*[@id='Invite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd'] | //*[@id='guestAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\" 3. Adding User from Wallet after Creating an Event\")")
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']")))
        // self.driver.find_element_by_xpath("//*[@content-desc='Invite'] | //*[@id='Invite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']      ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']  ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"4. Creating New Contact from wallet\")")
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Invite'] | //*[@id='Invite']")))
        // self.driver.find_element_by_xpath("//*[@content-desc='Invite'] | //*[@id='Invite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='newContactAdd'] | //*[@id='newContactAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName'] ").send_keys('Sonu')
        self.driver.find_element_by_xpath("//*[@content-desc='mobileCont'] | //*[@id='mobileCont'] ").send_keys('8937773737')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveContact'] | //*[@id='saveContact'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Sonu')
        self.driver.hide_keyboard()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='back'] | //*[@id='back']")))
        self.driver.find_element_by_xpath("//*[@content-desc='back'] | //*[@id='back'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"5. Adding Items in B-App with 1 Guest\")")
        self.driver.swipe(461, 1967, 461, 1702, 305)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.startActivity("com.vya_business", ".MainActivity")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='T8'] | //*[@id='T8']')))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Overview Overview'] | //*[@content-desc='Overview Overview'] | //*[@id='Overview Overview'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PaneerTikkaItem'] | //*[@id='PaneerTikkaItem'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='regularBtn'] | //*[@id='regularBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='extracheeseBtn'] | //*[@id='extracheeseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='sendItemsBtn'] | //*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Menu'] | //*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Paneer Tikka x 2'] | //*[@content-desc='PaneerTikka2regularextracheese PaneerTikka'] | //*[@id='PaneerTikka2regularextracheese PaneerTikka'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Pizza Quattro Stagioni x 2'] | //*[@content-desc='PizzaQuattroStagioni2 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni2 PizzaQuattroStagioni'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Menu'] | //*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number6'] | //*[@id='Number6'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number8'] | //*[@id='Number8'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='tipBtn'] | //*[@id='tipBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number4'] | //*[@id='Number4'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@text='Overview Overview'] | //*[@content-desc='Overview Overview'] | //*[@id='Overview Overview'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        self.driver.execute_script("seetest:client.sendText(\"6.Adding Items & 2 or more guests in B-App \")")
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd'] | //*[@id='guestAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers'] ").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("com.vya_business", ".MainActivity")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='T8'] | //*[@id='T8']')))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest2Card'] | //*[@id='Guest2Card'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest3Card'] | //*[@id='Guest3Card'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addGuestBtn'] | //*[@id='addGuestBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest4Card'] | //*[@id='Guest4Card'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']")))
        // self.driver.find_element_by_xpath("//*[@content-desc=''] | //*[@id='']").click()
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard'] ").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='Invite'] | //*[@id='Invite'] ").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Invite'] | //*[@id='Invite']")))
        self.driver.startActivity("com.vya_business", ".MainActivity")
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='In ProgressOrderCard'] | //*[@id='In ProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Pasta & PizzaBtn'] | //*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='PizzaRucolaeParmigianoItem'] | //*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem'] ").click()
        self.driver.find_element_by_xpath("//*[@text='FreshbellpepperBtn'] | //*[@content-desc='FreshbellpepperBtn'] | //*[@id='FreshbellpepperBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Pasta & PizzaBtn'] | //*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='PizzaRucolaeParmigianoItem'] | //*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem'] ").click()
        self.driver.find_element_by_xpath("//*[@text='addNewCustomSelection'] | //*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection'] ").click()
        self.driver.find_element_by_xpath("//*[@text='FreshchampignonsBtn'] | //*[@content-desc='FreshchampignonsBtn'] | //*[@id='FreshchampignonsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Pasta & PizzaBtn'] | //*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='PizzaRucolaeParmigianoItem'] | //*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem'] ").click()
        self.driver.find_element_by_xpath("//*[@text='addNewCustomSelection'] | //*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection'] ").click()
        self.driver.find_element_by_xpath("//*[@text='CookedhamBtn'] | //*[@content-desc='CookedhamBtn'] | //*[@id='CookedhamBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='PizzaQuattroStagioniItem'] | //*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewGuest'] | //*[@id='addNewGuest'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAll'] | //*[@id='selectAll']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='sendItemsBtn'] | //*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Menu'] | //*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano6Freshchampignons PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano6Freshchampignons PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano6Freshbellpepper PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano6Freshbellpepper PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano6Cookedham PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano6Cookedham PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni6 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni6 PizzaQuattroStagioni']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Menu'] | //*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest2select'] | //*[@id='Guest2select'] ").click()
        self.driver.swipe(827, 1866, 430, 1866, 217)
        self.driver.find_element_by_xpath("//*[@content-desc='Guest4select'] | //*[@id='Guest4select'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest5select'] | //*[@id='Guest5select'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest3Card'] | //*[@id='Guest3Card'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='paidCashPaymentBtn'] | //*[@id='paidCashPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number3'] | //*[@id='Number3'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest5select'] | //*[@id='Guest5select'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@text='Overview Overview'] | //*[@content-desc='Overview Overview'] | //*[@id='Overview Overview'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn'] ").click()
        self.driver.press_keycode(3) # home

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
