import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class Payments(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'Payments'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testPayments(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Payment Methods in B-App -  Cash\")")
        self.driver.execute_script("seetest:client.sendText(\"2. Host is Paying for Others- b app\")")
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Any'] | //*[@id='Any']")))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd'] | //*[@id='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T8'] | //*[@id='T8']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperBtn'] | //*[@id='FreshbellpepperBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshchampignonsBtn'] | //*[@id='FreshchampignonsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='CookedhamBtn'] | //*[@id='CookedhamBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano2Freshchampignons PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano2Freshchampignons PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano2Freshbellpepper PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano2Freshbellpepper PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni2 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni2 PizzaQuattroStagioni']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano2Cookedham PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano2Cookedham PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number1'] | //*[@id='Number1']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 1).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='tipBtn'] | //*[@id='tipBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number9'] | //*[@id='Number9']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Decimal point'] | //*[@id='Decimal point']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number1'] | //*[@id='Number1']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number3'] | //*[@id='Number3']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Decimal point'] | //*[@id='Decimal point']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number4'] | //*[@id='Number4']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.execute_script("seetest:client.sendText(\"3. Payment Methods in B-App -  Epayment\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Any'] | //*[@id='Any']")))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd'] | //*[@id='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T8'] | //*[@id='T8']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebabItem'] | //*[@id='MuttonSeekhKebabItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chutneyBtn'] | //*[@id='chutneyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebabItem'] | //*[@id='MuttonSeekhKebabItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chutneyBtn'] | //*[@id='chutneyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsBtn'] | //*[@id='4pcsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebab2chutney MuttonSeekhKebab'] | //*[@id='MuttonSeekhKebab2chutney MuttonSeekhKebab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebab24pcschutney MuttonSeekhKebab'] | //*[@id='MuttonSeekhKebab24pcschutney MuttonSeekhKebab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni2 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni2 PizzaQuattroStagioni']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='tipBtn'] | //*[@id='tipBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Decimal point'] | //*[@id='Decimal point']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='epaymentBtn'] | //*[@id='epaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number1'] | //*[@id='Number1']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.execute_script("seetest:client.sendText(\"4. Payment Methods in B-App -  Food voucher\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Any'] | //*[@id='Any']")))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd'] | //*[@id='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T8'] | //*[@id='T8']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='CrispyThaiSpringRollsItem'] | //*[@id='CrispyThaiSpringRollsItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='6pcsBtn'] | //*[@id='6pcsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='CrispyThaiSpringRolls26pcs CrispyThaiSpringRolls'] | //*[@id='CrispyThaiSpringRolls26pcs CrispyThaiSpringRolls']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni2 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni2 PizzaQuattroStagioni']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='foodVoucherBtn'] | //*[@id='foodVoucherBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='foodVoucher10CounterIncrement'] | //*[@id='foodVoucher10CounterIncrement']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputVoucher'] | //*[@id='inputVoucher']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.execute_script("seetest:client.sendText(\"5. Payment Methods in B-App -  All 3 modes of payment \")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Any'] | //*[@id='Any']")))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd'] | //*[@id='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T8'] | //*[@id='T8']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='SpaghettiAglioeOlioItem'] | //*[@id='SpaghettiAglioeOlioItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperBtn'] | //*[@id='FreshbellpepperBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='SpaghettiAglioeOlio2Freshbellpepper SpaghettiAglioeOlio'] | //*[@id='SpaghettiAglioeOlio2Freshbellpepper SpaghettiAglioeOlio']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni2 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni2 PizzaQuattroStagioni']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='tipBtn'] | //*[@id='tipBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number1'] | //*[@id='Number1']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number3'] | //*[@id='Number3']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='epaymentBtn'] | //*[@id='epaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Decimal point'] | //*[@id='Decimal point']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='foodVoucherBtn'] | //*[@id='foodVoucherBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='foodVoucher10CounterIncrement'] | //*[@id='foodVoucher10CounterIncrement']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputVoucher'] | //*[@id='inputVoucher']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.execute_script("seetest:client.sendText(\"6. pdf generation\")")
        self.driver.find_element_by_xpath("//*[@content-desc='Assign/Split Assign/Split'] | //*[@id='Assign/Split Assign/Split']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventInvoice'] | //*[@id='eventInvoice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='printNow'] | //*[@id='printNow']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='individualInvoice'] | //*[@id='individualInvoice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='printNow'] | //*[@id='printNow']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
