import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class pdf(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'pdf'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testpdf(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Payment by Individuals\")")
        // self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        // self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        // self.driver.hide_keyboard()
        // self.driver.swipe(363, 996, 360, 672, 168)
        // WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        // self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn'] ").click()
        // WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        // self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Roopa')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaInvite'] | //*[@id='RoopaInvite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers'] ").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@text='NooluNagaInviteCard'] | //*[@content-desc='NooluNagaInviteCard'] | //*[@id='NooluNagaInviteCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("com.vya_business", ".MainActivity")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T19AssignAnyBtn'] | //*[@id='T19AssignAnyBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PaneerTikkaItem'] | //*[@id='PaneerTikkaItem'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='regularBtn'] | //*[@id='regularBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='extracheeseBtn'] | //*[@id='extracheeseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Pasta & PizzaBtn'] | //*[@id='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniItem'] | //*[@id='PizzaQuattroStagioniItem'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='sendItemsBtn'] | //*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Menu'] | //*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PaneerTikka3regularextracheese PaneerTikka'] | //*[@id='PaneerTikka3regularextracheese PaneerTikka']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni3 PizzaQuattroStagioni'] | //*[@id='PizzaQuattroStagioni3 PizzaQuattroStagioni']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Menu'] | //*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1Card'] | //*[@id='Guest1Card'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='paidCashPaymentBtn'] | //*[@id='paidCashPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number3'] | //*[@id='Number3'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.swipe(509, 645, 509, 1315, 256)
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number3'] | //*[@id='Number3'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard']")))
        self.driver.swipe(509, 645, 509, 1315, 256)
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number3'] | //*[@id='Number3'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number5'] | //*[@id='Number5'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.execute_script("seetest:client.sendText(\"2. Generate PDF for Entire Event\")")
        self.driver.find_element_by_xpath("//*[@text='Assign/Split Assign/Split'] | //*[@content-desc='Assign/Split Assign/Split'] | //*[@id='Assign/Split Assign/Split'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@text='addItemsBtn'] | //*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@text='addItemsBtn'] | //*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@text='eventInvoice'] | //*[@content-desc='eventInvoice'] | //*[@id='eventInvoice'] ").click()
        self.driver.find_element_by_xpath("//*[@text='printNow'] | //*[@content-desc='printNow'] | //*[@id='printNow'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.execute_script("seetest:client.sendText(\"3. Generate PDF after Event Completion (Individual)\")")
        self.driver.find_element_by_xpath("//*[@text='backButton'] | //*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@text='addItemsBtn'] | //*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@text='addItemsBtn'] | //*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='individualInvoice'] | //*[@id='individualInvoice'] ").click()
        self.driver.find_element_by_xpath("//*[@text='NooluNagaselect'] | //*[@content-desc='NooluNagaselect'] | //*[@id='NooluNagaselect'] ").click()
        self.driver.find_element_by_xpath("//*[@text='printNow'] | //*[@content-desc='printNow'] | //*[@id='printNow'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@text='backButton'] | //*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@text='Overview Overview'] | //*[@content-desc='Overview Overview'] | //*[@id='Overview Overview'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn'] ").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
