import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class Pre_order(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'Pre-order'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testPre_order(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Adding More Items from Cart\")")
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65'] | //*[@id='Chicken65']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.execute_script("seetest:client.sendText(\"2.  add and reduce the items in cart and menu screen.\")")
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoInc'] | //*[@id='PizzaRucolaeParmigianoInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoInc'] | //*[@id='PizzaRucolaeParmigianoInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterMinus'] | //*[@id='counterMinus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartAddItems'] | //*[@id='cartAddItems']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cheesy-comfort-platescategory'] | //*[@id='cheesy-comfort-platescategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FourCheeseLasagnaInc'] | //*[@id='FourCheeseLasagnaInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='SliceProduct'] | //*[@id='SliceProduct']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        self.driver.find_element_by_xpath("//*[@content-desc='addgheeProduct'] | //*[@id='addgheeProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterMinus'] | //*[@id='counterMinus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='deleteCartYes'] | //*[@id='deleteCartYes']").click()
        self.driver.execute_script("seetest:client.sendText(\"3. edit the item from cart screen and check its editing correctly.\")")
        self.driver.find_element_by_xpath("//*[@content-desc='FourCheeseLasagnafinishedCard 7.42 €'] | //*[@id='FourCheeseLasagnafinishedCard 7.42 €']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AddMushroomProduct'] | //*[@id='AddMushroomProduct']").click()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='addgheeProduct'] | //*[@id='addgheeProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Gluten-FreePastaProduct'] | //*[@id='Gluten-FreePastaProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Pay € 265.70']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 60.49']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.execute_script("seetest:client.sendText(\"4. Host Preorders First and Invitee Does Not Preorder & add items with spcl instrn and without\")")
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='counterPlus' and ./parent::*[@text='counterMinus 1 counterPlus']]").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Roopa')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaInvite'] | //*[@id='RoopaInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('more crispyy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('less oil')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('more cheese')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus'] | //*[@id='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='SpicysalamiProduct'] | //*[@id='SpicysalamiProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Pay € 265.70']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 84.40']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaInviteCard'] | //*[@id='NooluNagaInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@content-desc='starterscategory'] | //*[@id='starterscategory']").click()
        self.driver.swipe(557, 2027, 569, 1821, 195)
        self.driver.swipe(557, 2027, 569, 1821, 195)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='HaraBharaKebabInc'] | //*[@id='HaraBharaKebabInc']")))
        self.driver.find_element_by_xpath("//*[@content-desc='HaraBharaKebab'] | //*[@id='HaraBharaKebab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsProduct'] | //*[@id='4pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceInc'] | //*[@id='ThaiGreenCurrywithJasmineRiceInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegProduct'] | //*[@id='vegProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsProduct'] | //*[@id='extrapeanutsProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Pay € 265.70']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 138.83']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cheesy-comfort-platescategory'] | //*[@id='cheesy-comfort-platescategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='regularBtn'] | //*[@id='regularBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AddTruffleOilBtn'] | //*[@id='AddTruffleOilBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBake2regularAddTruffleOil Macaroni&CheeseBake'] | //*[@id='Macaroni&CheeseBake2regularAddTruffleOil Macaroni&CheeseBake']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken651addmayomorecrispyy'] | //*[@id='Chicken651addmayomorecrispyy']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken651addmayolessoil'] | //*[@id='Chicken651addmayolessoil']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='HaraBharaKebab14pcs'] | //*[@id='HaraBharaKebab14pcs']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghi1Spicysalami'] | //*[@id='PizzaProsciuttoeFunghi1Spicysalami']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghi2Freshbellpeppermorecheese'] | //*[@id='PizzaProsciuttoeFunghi2Freshbellpeppermorecheese']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1vegchickentofuextrap'] | //*[@id='ThaiGreenCurrywithJasmineRice1vegchickentofuextrap']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.swipe(918, 375, 293, 375, 151)
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.execute_script("seetest:client.sendText(\"5. Host Preorders First and Invitee Does Not Preorder & add items with spcl instrn and without\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='counterPlus' and ./parent::*[@text='counterMinus 1 counterPlus']]").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.swipe(351, 1975, 351, 1521, 184)
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='starterscategory'] | //*[@id='starterscategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='starterscategory'] | //*[@id='starterscategory']").click()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='VegManchurianInc'] | //*[@id='VegManchurianInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='gravyProduct'] | //*[@id='gravyProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='extrasauceProduct'] | //*[@id='extrasauceProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('Spicyy ')
        self.driver.hide_keyboard()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='VegManchurianInc'] | //*[@id='VegManchurianInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='gravyProduct'] | //*[@id='gravyProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='extrasauceProduct'] | //*[@id='extrasauceProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('Crispyy ')
        self.driver.hide_keyboard()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='VegManchurianInc'] | //*[@id='VegManchurianInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='gravyProduct'] | //*[@id='gravyProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='extrasauceProduct'] | //*[@id='extrasauceProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('More sauce  ')
        self.driver.hide_keyboard()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']")))
        self.driver.swipe(854, 518, 496, 490, 418)
        self.driver.find_element_by_xpath("//*[@content-desc='cheesy-comfort-platescategory'] | //*[@id='cheesy-comfort-platescategory']").click()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='FourCheeseLasagnaInc'] | //*[@id='FourCheeseLasagnaInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='SliceProduct'] | //*[@id='SliceProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FourCheeseLasagnaInc'] | //*[@id='FourCheeseLasagnaInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AddMushroomProduct'] | //*[@id='AddMushroomProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniInc'] | //*[@id='PizzaQuattroStagioniInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioniInc'] | //*[@id='PizzaQuattroStagioniInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('Extra sauce  ')
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Pay € 265.70']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 530.33']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 7).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Cheesy & Comfort PlatesBtn'] | //*[@id='Cheesy & Comfort PlatesBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='regularBtn'] | //*[@id='regularBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AddTruffleOilBtn'] | //*[@id='AddTruffleOilBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAll'] | //*[@id='selectAll']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBake2regularAddTruffleOil Macaroni&CheeseBake'] | //*[@id='Macaroni&CheeseBake2regularAddTruffleOil Macaroni&CheeseBake']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='VegManchurian1gravyextrasauceSpicyy'] | //*[@id='VegManchurian1gravyextrasauceSpicyy']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='VegManchurian1gravyextrasauceMoresauce'] | //*[@id='VegManchurian1gravyextrasauceMoresauce']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='VegManchurian1gravyextrasauceCrispyy'] | //*[@id='VegManchurian1gravyextrasauceCrispyy']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FourCheeseLasagna1SliceGluten-FreePasta'] | //*[@id='FourCheeseLasagna1SliceGluten-FreePasta']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FourCheeseLasagna1AddMushroom'] | //*[@id='FourCheeseLasagna1AddMushroom']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaQuattroStagioni1Extrasauce'] | //*[@id='PizzaQuattroStagioni1Extrasauce']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.swipe(918, 375, 293, 375, 151)
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaselect'] | //*[@id='NooluNagaselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.execute_script("seetest:client.sendText(\"6. Host Does Not Preorder, Participant Preorders First & with diff options ans spcl instruction.\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='counterPlus' and ./parent::*[@text='counterMinus 1 counterPlus']]").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.swipe(351, 1975, 351, 1521, 184)
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.swipe(351, 1975, 351, 1521, 184)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@content-desc='starterscategory'] | //*[@id='starterscategory']").click()
        self.driver.swipe(590, 2027, 809, 512, 186)
        self.driver.swipe(590, 2027, 809, 512, 186)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.find_element_by_xpath("//*[@content-desc='HaraBharaKebabInc'] | //*[@id='HaraBharaKebabInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsProduct'] | //*[@id='4pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceInc'] | //*[@id='ThaiGreenCurrywithJasmineRiceInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegProduct'] | //*[@id='vegProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsProduct'] | //*[@id='extrapeanutsProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inputSplIns'] | //*[@id='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Pay € 265.70']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 138.83']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='starterscategory'] | //*[@id='starterscategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='starterscategory'] | //*[@id='starterscategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebab'] | //*[@id='MuttonSeekhKebab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='2pcsProduct'] | //*[@id='2pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chutneyProduct'] | //*[@id='chutneyProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.execute_script("seetest:client.sendText(\"7.  add coupon and remove it and again add check the the total. \")")
        self.driver.find_element_by_xpath("//*[@content-desc='applyCoupon'] | //*[@id='applyCoupon']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='6% OFFER'] | //*[@id='6% OFFER']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Pay € 265.70']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 249.76]").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 7).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']")))
        self.driver.swipe(854, 518, 496, 490, 418)
        self.driver.find_element_by_xpath("//*[@content-desc='Cheesy & Comfort PlatesBtn'] | //*[@id='Cheesy & Comfort PlatesBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='regularBtn'] | //*[@id='regularBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AddTruffleOilBtn'] | //*[@id='AddTruffleOilBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebab12pcschutney MuttonSeekhKebab'] | //*[@id='MuttonSeekhKebab12pcschutney MuttonSeekhKebab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBake2regularAddTruffleOil Macaroni&CheeseBake'] | //*[@id='Macaroni&CheeseBake2regularAddTruffleOil Macaroni&CheeseBake']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='HaraBharaKebab14pcs HaraBharaKebab'] | //*[@id='HaraBharaKebab14pcs HaraBharaKebab']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1vegchickentofuextrap ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1vegchickentofuextrap ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.swipe(918, 375, 293, 375, 151)
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
