import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class StatusVerification(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'StatusVerification'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testStatusVerification(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Confirmation pending -b app\")")
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        self.driver.find_element_by_xpath("//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName']").send_keys('Roopa')
        self.driver.find_element_by_xpath("//*[@content-desc='lastName'] | //*[@id='lastName']").send_keys('D')
        self.driver.find_element_by_xpath("//*[@content-desc='anyBtn'] | //*[@id='anyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='mobileInputBtn'] | //*[@id='mobileInputBtn']").send_keys('9686496589')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveBtn'] | //*[@id='saveBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='saveBtn'] | //*[@id='saveBtn']")))
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Nylai KitchenInviteCard'] | //*[@id='Nylai KitchenInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.execute_script("seetest:client.sendText(\"2. Reserved status - b- app\")")
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Allow'] | //*[@id='Allow']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Home'] | //*[@id='Home']").click()
        self.driver.swipe(409, 1936, 409, 1572, 222)
        self.driver.swipe(409, 1936, 409, 1572, 222)
        WebDriverWait(self.driver, 8).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Allow'] | //*[@id='Allow']")))
        self.driver.execute_script("seetest:client.sendText(\"3. Event declination from b-app\")")
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        self.driver.find_element_by_xpath("//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName']").send_keys('Roopa')
        self.driver.find_element_by_xpath("//*[@content-desc='lastName'] | //*[@id='lastName']").send_keys('D')
        self.driver.find_element_by_xpath("//*[@content-desc='anyBtn'] | //*[@id='anyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='mobileInputBtn'] | //*[@id='mobileInputBtn']").send_keys('9686496589')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveBtn'] | //*[@id='saveBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='saveBtn'] | //*[@id='saveBtn']")))
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Nylai KitchenInviteCard'] | //*[@id='Nylai KitchenInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventDecline'] | //*[@id='eventDecline']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Allow'] | //*[@id='Allow']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Home'] | //*[@id='Home']").click()
        self.driver.swipe(409, 1936, 409, 1572, 222)
        self.driver.swipe(409, 1936, 409, 1572, 222)
        WebDriverWait(self.driver, 8).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Allow'] | //*[@id='Allow']")))
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"4. pre-order status c-app\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Any'] | //*[@id='Any']")))
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("5. cancelled c-app & b-app").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='walletTab'] | //*[@id='walletTab']")))
        self.driver.find_element_by_xpath("//*[@content-desc='optionThree'] | //*[@id='optionThree']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Home'] | //*[@id='Home']")))
        self.driver.swipe(409, 1936, 409, 1572, 222)
        self.driver.swipe(409, 1936, 409, 1572, 222)
        self.driver.execute_script("seetest:client.sendText(\"6. Menu - c app\")")
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TomYumSoupInc'] | //*[@id='TomYumSoupInc']")))
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.find_element_by_xpath("//*[@content-desc='TomYumSoupInc'] | //*[@id='TomYumSoupInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='prawnProduct'] | //*[@id='prawnProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='CONFIRM ORDER'] | //*[@id='CONFIRM ORDER']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderConfirmedMenu'] | //*[@id='orderConfirmedMenu']").click()
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.press_keycode(3) # home
        self.driver.execute_script("seetest:client.sendText(\"7. Order status - b app\")")
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Allow'] | //*[@id='Allow']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Allow'] | //*[@id='Allow']")))
        self.driver.find_element_by_xpath("//*[@content-desc='OrderOrderCard'] | //*[@id='OrderOrderCard']").click()
        self.driver.execute_script("seetest:client.sendText(\"8. In progress - b-app\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Cheesy & Comfort PlatesBtn'] | //*[@id='Cheesy & Comfort PlatesBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBakeItem'] | //*[@id='Macaroni&CheeseBakeItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='regularBtn'] | //*[@id='regularBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AddTruffleOilBtn'] | //*[@id='AddTruffleOilBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAll'] | //*[@id='selectAll']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Macaroni&CheeseBake1regularAddTruffleOil Macaroni&CheeseBake'] | //*[@id='Macaroni&CheeseBake1regularAddTruffleOil Macaroni&CheeseBake']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='TomYumSoup1vegchickenprawn TomYumSoup'] | //*[@id='TomYumSoup1vegchickenprawn TomYumSoup']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.swipe(918, 375, 293, 375, 151)
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.execute_script("seetest:client.sendText(\"9. Serve status - b -app\")")
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.execute_script("seetest:client.sendText(\"10. Payment - b-app\")")
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']")))
        self.driver.press_keycode(3) # home
        self.driver.execute_script("seetest:client.sendText(\"11. Payment Requested -c-app\")")
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen2Card PAYMENT REQUESTED'] | //*[@id='NylaiKitchen2Card PAYMENT REQUESTED']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        self.driver.execute_script("seetest:client.sendText(\"12. Payment done c-app\")")
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PaymentOrderCard'] | //*[@id='PaymentOrderCard']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number2'] | //*[@id='Number2']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='PaymentDoneOrderCard'] | //*[@id='PaymentDoneOrderCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='PaymentDoneOrderCard'] | //*[@id='PaymentDoneOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='closeTableBtn'] | //*[@id='closeTableBtn']").click()
        self.driver.execute_script("seetest:client.sendText(\"13. Completed b-app\")")
        self.driver.find_element_by_xpath("//*[@content-desc='Home'] | //*[@id='Home']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDCompletedCard'] | //*[@id='RoopaDCompletedCard']")))
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.press_keycode(3) # home
        self.driver.execute_script("seetest:client.sendText(\"14. Completed c-app\")")
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='walletTab'] | //*[@id='walletTab']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard COMPLETED'] | //*[@id='NylaiKitchenCard COMPLETED']").click()
        self.driver.execute_script("seetest:client.sendText(\"15. Checking No-show status for the users \")")
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='counterPlus' and ./parent::*[@text='counterMinus 1 counterPlus']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='11:58'] | //*[@id='11:58']")))
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T19AssignAnyBtn'] | //*[@id='T19AssignAnyBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.swipe(610, 1540, 493, 990, 184)
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegBtn'] | //*[@id='vegBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addspicyBtn'] | //*[@id='addspicyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='tofuBtn'] | //*[@id='tofuBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsBtn'] | //*[@id='extrapeanutsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chickenBtn'] | //*[@id='chickenBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='extrasauceBtn'] | //*[@id='extrasauceBtn']").click()
        self.driver.find_element_by_xpath("//*[@XCElementType='XCUIElementTypeTextView']").send_keys('More spice')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chickenBtn'] | //*[@id='chickenBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoBtn'] | //*[@id='addmayoBtn']").click()
        self.driver.find_element_by_xpath("//*[@XCElementType='XCUIElementTypeTextView']").send_keys('Onions')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.swipe(848, 1851, 400, 1857, 207)
        self.driver.swipe(763, 1845, 339, 1851, 208)
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtns'] | //*[@id='assignProductsBtns']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1vegaddspicy ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1vegaddspicy ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1tofuextrapeanuts ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1tofuextrapeanuts ThaiGreenCurrywithJasmineRice']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1chickenaddmayoOnions ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1chickenaddmayoOnions ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1chickenextrasauceMor ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1chickenextrasauceMor ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue']").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue']").send_keys('Nylaii@06')
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn']").click()
        self.driver.execute_script("seetest:client.sendText(\"16. payment done status verification using c-app payment \")")
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard PAYMENT REQUESTED'] | //*[@id='NylaiKitchenCard PAYMENT REQUESTED']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDfinishedCard'] | //*[@id='RoopaDfinishedCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='payTotal'] | //*[@id='payTotal']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='proceedPayment'] | //*[@id='proceedPayment']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ePayment'] | //*[@id='ePayment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Card number']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Pay € 63.03']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='walletTab'] | //*[@id='walletTab']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PaymentDoneOrderCard'] | //*[@id='PaymentDoneOrderCard']").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
