import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class Create_ManageEventsfromB_App(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'Create&ManageEventsfromB-App'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testCreate_ManageEventsfromB_App(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Create an event from b-app when user declines \")")
        self.driver.find_element_by_xpath("//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName'] ").send_keys('Roopa')
        self.driver.find_element_by_xpath("//*[@content-desc='lastName'] | //*[@id='lastName'] ").send_keys('D')
        self.driver.find_element_by_xpath("//*[@content-desc='anyBtn'] | //*[@id='anyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='mobileInputBtn'] | //*[@id='mobileInputBtn'] ").send_keys('9686496589')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveBtn'] | //*[@id='saveBtn'] ").click()
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Nylai KitchenInviteCard'] | //*[@id='Nylai KitchenInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventDecline'] | //*[@id='eventDecline'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='eventDecline'] | //*[@id='eventDecline']")))
        self.driver.execute_script("seetest:client.sendText(\"2. Create an event from b-app when user Accepts\")")
        self.driver.startActivity("com.vya_business", ".MainActivity")
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName'] ").send_keys('Roopa')
        self.driver.find_element_by_xpath("//*[@content-desc='lastName'] | //*[@id='lastName'] ").send_keys('D')
        self.driver.find_element_by_xpath("//*[@content-desc='anyBtn'] | //*[@id='anyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='mobileInputBtn'] | //*[@id='mobileInputBtn'] ").send_keys('9686496589')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveBtn'] | //*[@id='saveBtn'] ").click()
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Nylai KitchenInviteCard'] | //*[@id='Nylai KitchenInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='starterscategory'] | //*[@id='starterscategory'] ").click()
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.find_element_by_xpath("//*[@content-desc='MuttonSeekhKebabInc'] | //*[@id='MuttonSeekhKebabInc'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='2pcsProduct'] | //*[@id='2pcsProduct'] ").click()
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.find_element_by_xpath("//*[@content-desc='chutneyProduct'] | //*[@id='chutneyProduct'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='cheesy-comfort-platescategory'] | //*[@id='cheesy-comfort-platescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cheesy-comfort-platescategory'] | //*[@id='cheesy-comfort-platescategory'] ").click()
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.find_element_by_xpath("//*[@content-desc='Cheese-StuffedGarlicBreadInc'] | //*[@id='Cheese-StuffedGarlicBreadInc'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='6pccsProduct'] | //*[@id='6pccsProduct'] ").click()
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.swipe(587, 1712, 593, 1621, 336)
        self.driver.find_element_by_xpath("//*[@content-desc='MarinaraDipProduct'] | //*[@id='MarinaraDipProduct'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        self.driver.find_element_by_xpath("//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']")))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.execute_script("seetest:client.sendText(\"3. Create an Event from B-App and invite user from wallet.\")")
        self.driver.startActivity("com.vya_business", ".MainActivity")
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName'] ").send_keys('Roopa')
        self.driver.find_element_by_xpath("//*[@content-desc='lastName'] | //*[@id='lastName'] ").send_keys('D')
        self.driver.find_element_by_xpath("//*[@content-desc='anyBtn'] | //*[@id='anyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='mobileInputBtn'] | //*[@id='mobileInputBtn'] ").send_keys('9686496589')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveBtn'] | //*[@id='saveBtn'] ").click()
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Nylai KitchenInviteCard'] | //*[@id='Nylai KitchenInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='Invite'] | //*[@id='Invite']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Noolu')
        self.driver.hide_keyboard()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NooluaInvite'] | //*[@id='NooluaInvite']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers'] ").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']")))
        self.driver.execute_script("seetest:client.sendText(\"4. cancel event from b-app when invitee is there.\")")
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='orderLater'] | //*[@id='orderLater']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']")))
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.startActivity("com.vya_business", ".MainActivity")
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='cancelEvent'] | //*[@id='cancelEvent']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cancelEvent'] | //*[@id='cancelEvent']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmEventBtn'] | //*[@id='confirmEventBtn']").click()
        WebDriverWait(self.driver, 8).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='confirmEventBtn'] | //*[@id='confirmEventBtn']")))
        self.driver.execute_script("seetest:client.sendText(\"5. Cancel Event from B-App -created from B-app.\")")
        self.driver.startActivity("com.vya_business", ".MainActivity")
        self.driver.find_element_by_xpath("//*[@content-desc='addNewEvent'] | //*[@id='addNewEvent']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='firstName'] | //*[@id='firstName'] ").send_keys('Roopa')
        self.driver.find_element_by_xpath("//*[@content-desc='lastName'] | //*[@id='lastName'] ").send_keys('D')
        self.driver.find_element_by_xpath("//*[@content-desc='anyBtn'] | //*[@id='anyBtn']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='surface-outer-layer'] | //*[@id='surface-outer-layer']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='mobileInputBtn'] | //*[@id='mobileInputBtn'] ").send_keys('9686496589')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='saveBtn'] | //*[@id='saveBtn']").click()
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Wallet'] | //*[@id='Wallet']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Nylai KitchenInviteCard'] | //*[@id='Nylai KitchenInviteCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.startActivity("com.vya_business", ".MainActivity")
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='cancelEvent'] | //*[@id='cancelEvent']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cancelEvent'] | //*[@id='cancelEvent']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmEventBtn'] | //*[@id='confirmEventBtn']").click()
        WebDriverWait(self.driver, 8).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='confirmEventBtn'] | //*[@id='confirmEventBtn']")))
        self.driver.execute_script("seetest:client.sendText(\"6. when we tranfer event from i waiter to another it has to delete from that partciular restro and check whether its reflected in selected restro.\")")
        self.driver.startActivity("com.vyaconsumer", ".MainActivity")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(461, 1967, 461, 1702, 305)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.startActivity("com.vya_business", ".MainActivity")
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Home'] | //*[@id='Home'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Home'] | //*[@id='Home']")))
        self.driver.find_element_by_xpath("//*[@content-desc='transferBtn'] | //*[@id='transferBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmEventBtn'] | //*[@id='confirmEventBtn']").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
