import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class Ordering(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'Ordering'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testOrdering(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Adding items with different modifiers & variants -5 users\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch'] ").send_keys('Aritro')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='AritroInvite'] | //*[@id='AritroInvite'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='chip'] | //*[@id='chip']')))
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']  ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab'] ").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='menuTab'] | //*[@id='menuTab']")))
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='menuLogout'] | //*[@id='menuLogout']")))
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('aritro@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']  ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@id='eventAccept'] ").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Orders'] | //*[@id='Orders']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ReservedOrderCard'] | //*[@id='ReservedOrderCard'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='T19AssignAnyBtn'] | //*[@id='T19AssignAnyBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='T0AssignAnyBtn'] | //*[@id='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='AssignTableBtn'] | //*[@id='AssignTableBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn'] ").click()
        self.driver.swipe(610, 1540, 493, 990, 184)
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegBtn'] | //*[@id='vegBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addspicyBtn'] | //*[@id='addspicyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='tofuBtn'] | //*[@id='tofuBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsBtn'] | //*[@id='extrapeanutsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chickenBtn'] | //*[@id='chickenBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='extrasauceBtn'] | //*[@id='extrasauceBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='specialInstructions'] | //*[@id='specialInstructions']").send_keys('More spice')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceItem'] | //*[@id='ThaiGreenCurrywithJasmineRiceItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='chickenBtn'] | //*[@id='chickenBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoBtn'] | //*[@id='addmayoBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='specialInstructions'] | //*[@id='specialInstructions']").send_keys('Onions')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.execute_script("seetest:client.sendText(\"2. split before serve \")")
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.swipe(848, 1851, 400, 1857, 207)
        self.driver.swipe(763, 1845, 339, 1851, 208)
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest2select'] | //*[@id='Guest2select']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtns'] | //*[@id='assignProductsBtns']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='addItemsBtn'] | //*[@id='addItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshchampignonsBtn'] | //*[@id='FreshchampignonsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianoItem'] | //*[@id='PizzaRucolaeParmigianoItem']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addNewCustomSelection'] | //*[@id='addNewCustomSelection']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='CookedhamBtn'] | //*[@id='CookedhamBtn']").click()
        self.driver.swipe(613, 1976, 593, 820, 120)
        self.driver.find_element_by_xpath("//*[@content-desc='specialInstructions'] | //*[@id='specialInstructions']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='applyOptionBtn'] | //*[@id='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignToBtn'] | //*[@id='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaselect'] | //*[@id='NooluNagaselect']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtn'] | //*[@id='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='backButton'] | //*[@id='backButton']")))
        self.driver.find_element_by_xpath("//*[@content-desc='backButton'] | //*[@id='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard']")))
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='inProgressOrderCard'] | //*[@id='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1vegaddspicy ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1vegaddspicy ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1tofuextrapeanuts ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1tofuextrapeanuts ThaiGreenCurrywithJasmineRice']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1chickenaddmayoOnions ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1chickenaddmayoOnions ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRice1chickenextrasauceMor ThaiGreenCurrywithJasmineRice'] | //*[@id='ThaiGreenCurrywithJasmineRice1chickenextrasauceMor ThaiGreenCurrywithJasmineRice']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano1Freshchampignons PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano1Freshchampignons PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigiano1Cookedham PizzaRucolaeParmigiano'] | //*[@id='PizzaRucolaeParmigiano1Cookedham PizzaRucolaeParmigiano']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderReadyBtn'] | //*[@id='orderReadyBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderCloseBtn'] | //*[@id='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Menu'] | //*[@id='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='logOutBtn'] | //*[@id='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='emailValue'] | //*[@id='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='passwordValue'] | //*[@id='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@content-desc='clickCheckBox'] | //*[@id='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='signInBtn'] | //*[@id='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Orders'] | //*[@id='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ServeOrderCard'] | //*[@id='ServeOrderCard'] ").click()
        self.driver.execute_script("seetest:client.sendText(\"3. trying to split splitted items \")")
        self.driver.find_element_by_xpath("//*[@content-desc='Assign/Split Assign/Split'] | //*[@id='Assign/Split Assign/Split']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRicecard'] | //*[@id='ThaiGreenCurrywithJasmineRicecard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtns'] | //*[@id='assignProductsBtns']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='closeModal'] | //*[@id='closeModal']").click()
        self.driver.execute_script("seetest:client.sendText(\"4. assigning item from 1 to another\")")
        // self.driver.find_element_by_xpath("//*[@content-desc='arrowBtn'] | //*[@id='arrowBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaselect'] | //*[@id='NooluNagaselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianocard'] | //*[@id='PizzaRucolaeParmigianocard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDselect'] | //*[@id='RoopaDselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtns'] | //*[@id='assignProductsBtns']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='closeModal'] | //*[@id='closeModal']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='assignProductsBtns'] | //*[@id='assignProductsBtns']")))
        self.driver.find_element_by_xpath("//*[@text='Overview Overview']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='selectAllItemsBtn'] | //*[@id='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn'] ").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='serveItemsBtn'] | //*[@id='serveItemsBtn']")))
        self.driver.execute_script("seetest:client.sendText(\"5. Split after serve \")")
        self.driver.find_element_by_xpath("//*[@content-desc='Assign/Split Assign/Split'] | //*[@id='Assign/Split Assign/Split']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='arrowBtn'] | //*[@id='arrowBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaselect'] | //*[@id='NooluNagaselect']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaRucolaeParmigianocard'] | //*[@id='PizzaRucolaeParmigianocard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='sendItemsBtn'] | //*[@id='sendItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaselect'] | //*[@id='NooluNagaselect']").click()
        self.driver.swipe(848, 1851, 400, 1857, 207)
        self.driver.swipe(848, 1851, 400, 1857, 207)
        self.driver.find_element_by_xpath("//*[@content-desc='Guest2select'] | //*[@id='Guest2select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='assignProductsBtns'] | //*[@id='assignProductsBtns']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='closeModal'] | //*[@id='closeModal']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='notifyPaymentBtn'] | //*[@id='notifyPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Payment Payment'] | //*[@id='Payment Payment']")))
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCard'] | //*[@id='RoopaDCard'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number7'] | //*[@id='Number7'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest1select'] | //*[@id='Guest1select'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Guest2select'] | //*[@id='Guest2select'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Apply'] | //*[@id='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='Apply'] | //*[@id='Apply']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.swipe(520, 1662, 537, 1086, 224)
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCard'] | //*[@id='NooluNagaCard']").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='cashPaymentBtn'] | //*[@id='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number1'] | //*[@id='Number1'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number0'] | //*[@id='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='userInputBtn'] | //*[@id='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='tipBtn'] | //*[@id='tipBtn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Number1'] | //*[@id='Number1'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='paymentConfirmBtn'] | //*[@id='paymentConfirmBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='Overview Overview'] | //*[@id='Overview Overview']").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
