import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class EventCancellations(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'EventCancellations'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testEventCancellations(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Host Cancels Event when Invitee Accepted\")")
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cancelBookingMe'] | //*[@id='cancelBookingMe']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaassign'] | //*[@id='NooluNagaassign']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmCancelBook'] | //*[@id='confirmCancelBook']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='yesGotIt'] | //*[@id='yesGotIt']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cancelReason'] | //*[@id='cancelReason']").send_keys('Booked wrong slot!')
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.execute_script("seetest:client.sendText(\"2. after changing the host while evnt cancellation check whether adding user/guest working or not.\")")
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']")))
        self.driver.execute_script("seetest:client.sendText(\"3. Host Cancels Event when Invitee Declined\")")
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventDecline'] | //*[@id='eventDecline']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='menuTab'] | //*[@id='menuTab']")))
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.execute_script("seetest:client.sendText(\"4. Participant Cancels Event\")")
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']")))
        self.driver.swipe(461, 1967, 461, 1702, 305)
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='orderLater'] | //*[@id='orderLater']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaCancelBookingCard'] | //*[@id='NooluNagaCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"5. Both Host and Participant Cancel Event\")")
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='menuTab'] | //*[@id='menuTab']")))
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"6. Host Cancels Event when Invitee Accepted after both preorder - After 15 min -Me Only\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']')))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityIdentifier='menuTab' or @accessibilityLabel='menuTab' or @name='menuTab' or @label='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@name='starterscategory' or @label='starterscategory']").click()
        self.driver.swipe(557, 2027, 569, 1821, 195)
        self.driver.swipe(557, 2027, 569, 1821, 195)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@value='HaraBharaKebab' or @name='HaraBharaKebab' or @label='HaraBharaKebab' or @accessibilityLabel='HaraBharaKebab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsProduct'] | //*[@id='4pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='confirmProduct' or @name='confirmProduct' or @label='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceInc'] | //*[@id='ThaiGreenCurrywithJasmineRiceInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegProduct'] | //*[@id='vegProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsProduct'] | //*[@id='extrapeanutsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inputSplIns' or @name='inputSplIns' or @label='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cancelBookingMe'] | //*[@id='cancelBookingMe']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaassign'] | //*[@id='NooluNagaassign']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmCancelBook'] | //*[@id='confirmCancelBook']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='yesGotIt'] | //*[@id='yesGotIt']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"7. only host preorders & cancels the event & guest - After 15 min -Me Only\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']')))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"8. Host Cancels Event when Invitee Accepted after both preorder - After 15 min - Cancel for all\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("xpath=//*[@content-desc='chip-container'] | //*[@id='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']')))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityIdentifier='menuTab' or @accessibilityLabel='menuTab' or @name='menuTab' or @label='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@name='starterscategory' or @label='starterscategory']").click()
        self.driver.swipe(557, 2027, 569, 1821, 195)
        self.driver.swipe(557, 2027, 569, 1821, 195)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@value='HaraBharaKebab' or @name='HaraBharaKebab' or @label='HaraBharaKebab' or @accessibilityLabel='HaraBharaKebab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsProduct'] | //*[@id='4pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='confirmProduct' or @name='confirmProduct' or @label='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceInc'] | //*[@id='ThaiGreenCurrywithJasmineRiceInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegProduct'] | //*[@id='vegProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsProduct'] | //*[@id='extrapeanutsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inputSplIns' or @name='inputSplIns' or @label='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='cancelBookingAll' or @name='cancelBookingAll' or @label='cancelBookingAll' or @accessibilityIdentifier='cancelBookingAll'] ").click()
        self.driver.find_element_by_xpath("//*[@value='minsLeft']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"9. Host Cancels Event when Invitee Accepted after both preorder - Before 15 min - Cancel for all\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@value='Not Sure']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityIdentifier='menuTab' or @accessibilityLabel='menuTab' or @name='menuTab' or @label='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@name='starterscategory' or @label='starterscategory']").click()
        self.driver.swipe(557, 2027, 569, 1821, 195)
        self.driver.swipe(557, 2027, 569, 1821, 195)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@value='HaraBharaKebab' or @name='HaraBharaKebab' or @label='HaraBharaKebab' or @accessibilityLabel='HaraBharaKebab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsProduct'] | //*[@id='4pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='confirmProduct' or @name='confirmProduct' or @label='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceInc'] | //*[@id='ThaiGreenCurrywithJasmineRiceInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegProduct'] | //*[@id='vegProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsProduct'] | //*[@id='extrapeanutsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inputSplIns' or @name='inputSplIns' or @label='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='cancelBookingAll' or @name='cancelBookingAll' or @label='cancelBookingAll' or @accessibilityIdentifier='cancelBookingAll'] ").click()
        self.driver.find_element_by_xpath("//*[@value='minsLeft']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"10. Host Cancels Event when Invitee Accepted after both preorder - before 15 min -Me Only\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='contactSearch'] | //*[@id='contactSearch']").send_keys('Noolu')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluInvite'] | //*[@id='NooluInvite']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@value='Not Sure']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='chip-container']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']')))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityIdentifier='menuTab' or @accessibilityLabel='menuTab' or @name='menuTab' or @label='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail']").send_keys('noolu@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword']").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']")))
        self.driver.find_element_by_xpath("//*[@content-desc='RoopaDInviteCard'] | //*[@content-desc='RoopaDInviteCard'] | //*[@id='RoopaDInviteCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='eventAccept'] | //*[@content-desc='eventAccept'] | //*[@id='eventAccept']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@name='starterscategory' or @label='starterscategory']").click()
        self.driver.swipe(557, 2027, 569, 1821, 195)
        self.driver.swipe(557, 2027, 569, 1821, 195)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='TagliatelledelloChefInc'] | //*[@id='TagliatelledelloChefInc']")))
        self.driver.find_element_by_xpath("//*[@value='HaraBharaKebab' or @name='HaraBharaKebab' or @label='HaraBharaKebab' or @accessibilityLabel='HaraBharaKebab'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='4pcsProduct'] | //*[@id='4pcsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='confirmProduct' or @name='confirmProduct' or @label='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@content-desc='ThaiGreenCurrywithJasmineRiceInc'] | //*[@id='ThaiGreenCurrywithJasmineRiceInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='vegProduct'] | //*[@id='vegProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@content-desc='extrapeanutsProduct'] | //*[@id='extrapeanutsProduct']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inputSplIns' or @name='inputSplIns' or @label='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuTab'] | //*[@id='menuTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='menuLogout'] | //*[@id='menuLogout']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='loginEmail'] | //*[@id='loginEmail'] ").send_keys('roopa@xorstack.com')
        self.driver.find_element_by_xpath("//*[@content-desc='loginPassword'] | //*[@id='loginPassword'] ").send_keys('12345')
        self.driver.hide_keyboard()
        self.driver.swipe(363, 996, 360, 672, 168)
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='signIn'] | //*[@id='signIn']")))
        self.driver.find_element_by_xpath("//*[@content-desc='signIn'] | //*[@id='signIn']").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Allow Once']')))
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchenCard'] | //*[@id='NylaiKitchenCard']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cancelBookingMe'] | //*[@id='cancelBookingMe']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='NooluNagaassign'] | //*[@id='NooluNagaassign']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmCancelBook'] | //*[@id='confirmCancelBook']").click()
        // self.driver.find_element_by_xpath("//*[@content-desc='yesGotIt'] | //*[@id='yesGotIt']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"11. only host preorders & cancels the event & guest -before 15 min -Me Only\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd'] ").click()
        self.driver.find_element_by_xpath("//*[@content-desc='inviteUsers'] | //*[@id='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@value='Not Sure']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='chip-container']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']")))
        self.driver.find_element_by_xpath("//*[@content-desc='bookAppoitment'] | //*[@id='bookAppoitment']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']")))
        self.driver.find_element_by_xpath("//*[@content-desc='preOrderBooking'] | //*[@id='preOrderBooking']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='Tagliatelle al Salmone'] | //*[@id='Tagliatelle al Salmone']')))
        self.driver.find_element_by_xpath("//*[@content-desc='Chicken65Inc'] | //*[@id='Chicken65Inc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='addmayoProduct'] | //*[@id='addmayoProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='pasta-pizzacategory'] | //*[@id='pasta-pizzacategory']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='PizzaProsciuttoeFunghiInc'] | //*[@id='PizzaProsciuttoeFunghiInc']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='FreshbellpepperProduct'] | //*[@id='FreshbellpepperProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='homeTab'] | //*[@id='homeTab']").click()
        self.driver.execute_script("seetest:client.sendText(\"12. Pickup cancellation.\")")
        self.driver.find_element_by_xpath("//*[@content-desc='NylaiKitchen'] | //*[@id='NylaiKitchen']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@value='Pickup']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='chip']").click()
        self.driver.find_element_by_xpath("//*[@value='browseMenu']").click()
        self.driver.find_element_by_xpath("//*[@value='cheesy-comfort-platescategory']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        self.driver.find_element_by_xpath("//*[@value='Cheese-StuffedGarlicBreadInc']").click()
        self.driver.find_element_by_xpath("//*[@value='6pccsProduct']").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        self.driver.find_element_by_xpath("//*[@value='MarinaraDipProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.swipe(593, 2133, 684, 1090, 169)
        self.driver.swipe(578, 1487, 587, 984, 160)
        self.driver.swipe(593, 2133, 684, 1090, 169)
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@content-desc='thai-street-food-favoritescategory'] | //*[@id='thai-street-food-favoritescategory']")))
        self.driver.find_element_by_xpath("//*[@value='TomYumSoupInc']").click()
        self.driver.find_element_by_xpath("//*[@value='chickenProduct']").click()
        self.driver.swipe(569, 2142, 578, 1503, 201)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inputSplIns' or @name='inputSplIns' or @label='inputSplIns']").send_keys('Spicy')
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@content-desc='confirmProduct'] | //*[@id='confirmProduct']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartImage'] | //*[@id='cartImage']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='cartCheckout'] | //*[@id='cartCheckout']").click()
        WebDriverWait(self.driver, 5).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='primary_button']')))
        self.driver.find_element_by_xpath("xpath=//*[@id='primary_button']").click()
        WebDriverWait(self.driver, 6).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@content-desc='YES, GOT IT'] | //*[@id='YES, GOT IT']')))
        self.driver.find_element_by_xpath("//*[@content-desc='pickUpOrderConfirm'] | //*[@id='pickUpOrderConfirm']").click()
        self.driver.swipe(600, 2178, 645, 1809, 217)
        // self.driver.find_element_by_xpath("//*[@content-desc='RoopaDCancelBookingCard'] | //*[@id='RoopaDCancelBookingCard']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionOne'] | //*[@id='optionOne']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='optionSubmit'] | //*[@id='optionSubmit']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='BOOKING CANCELLED'] | //*[@id='BOOKING CANCELLED']").click()
        self.driver.find_element_by_xpath("//*[@content-desc='walletTab'] | //*[@id='walletTab']").click()

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
