import unittest
import time
from appium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions


class EventBooking2(unittest.TestCase):
    reportDirectory = 'reports'
    reportFormat = 'xml'
    dc = {}
    testName = 'EventBooking2'
    driver = None
    
    def setUp(self):
        self.dc['reportDirectory'] = self.reportDirectory
        self.dc['reportFormat'] = self.reportFormat
        self.dc['testName'] = self.testName
        self.dc['udid'] = ''
        self.dc['platformName'] = 'android'
        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',self.dc)

    def testEventBooking2(self):
        self.driver.execute_script("seetest:client.sendText(\"1. Book an Event with Guest for 2 hours\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@name='NylaiKitchen' or @label='NylaiKitchen' or @accessibilityLabel='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@name='NylaiKitchen' or @label='NylaiKitchen' or @accessibilityLabel='NylaiKitchen'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='2 hrs' or @name='2 hrs' or @label='2 hrs'] ").click()
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@value='MessageInput Write a short message about the event...' or @accessibilityLabel='MessageInput' or @name='MessageInput' or @label='MessageInput' or @accessibilityIdentifier='MessageInput' or @content-desc='MessageInput'] ").send_keys('Lets go!!!')
        self.driver.find_element_by_xpath("//*[@value='Sendmessage' or @accessibilityLabel='Sendmessage' or @name='Sendmessage' or @label='Sendmessage' or @accessibilityIdentifier='Sendmessage' or @content-desc='Sendmessage'] ").click()
        self.driver.swipe(363, 996, 360, 672, 168)
        self.driver.find_element_by_xpath("xpath=//*[@accessibilityLabel='chip-container'] ").click()
        self.driver.find_element_by_xpath("//*[@name='bookAppoitment' or @label='bookAppoitment'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='NylaiKitchenCard' or @name='NylaiKitchenCard' or @label='NylaiKitchenCard' or @accessibilityIdentifier='NylaiKitchenCard' or @content-desc='NylaiKitchenCard' or @value='NylaiKitchenCard']")))
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@name='Allow' or @label='Allow']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Orders' or @name='Orders' or @label='Orders'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='ReservedOrderCard' or @name='ReservedOrderCard' or @label='ReservedOrderCard']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='ReservedOrderCard' or @name='ReservedOrderCard' or @label='ReservedOrderCard'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@accessibilityLabel='T8']')))
        self.driver.find_element_by_xpath("//*[@value='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='AssignTableBtn' or @name='AssignTableBtn' or @label='AssignTableBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='addItemsBtn' or @name='addItemsBtn' or @label='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='addItemsBtn' or @name='addItemsBtn' or @label='addItemsBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@value='Pasta & PizzaBtn' or @label='Pasta & PizzaBtn' or @name='Pasta & PizzaBtn']")))
        self.driver.find_element_by_xpath("//*[@value='Pasta & PizzaBtn' or @label='Pasta & PizzaBtn' or @name='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='TagliatellealMontiItem'  or @accessibilityLabel='TagliatellealMontiItem'  or @name='TagliatellealMontiItem'  or @label='TagliatellealMontiItem'  or @content-desc='TagliatellealMontiItem'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='FreshchampignonsBtn'  or @name='FreshchampignonsBtn'  or @label='FreshchampignonsBtn'  or @accessibilityIdentifier='FreshchampignonsBtn'  or @content-desc='FreshchampignonsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@value='Pasta & PizzaBtn' or @label='Pasta & PizzaBtn' or @name='Pasta & PizzaBtn']")))
        self.driver.find_element_by_xpath("//*[@value='Pasta & PizzaBtn' or @label='Pasta & PizzaBtn' or @name='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='TagliatellealMontiItem'  or @accessibilityLabel='TagliatellealMontiItem'  or @name='TagliatellealMontiItem'  or @label='TagliatellealMontiItem'  or @content-desc='TagliatellealMontiItem'] ").click()
        self.driver.find_element_by_xpath("(//*[@value='addNewCustomSelection'   or @name='addNewCustomSelection'   or @label='addNewCustomSelection'   or @accessibilityLabel='addNewCustomSelection'])[1] ").click()
        self.driver.find_element_by_xpath("//*[@value='CookedhamBtn'  or @accessibilityLabel='CookedhamBtn'  or @label='CookedhamBtn'  or @name='CookedhamBtn'  or @accessibilityIdentifier='CookedhamBtn'  or @content-desc='CookedhamBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@value='Cheesy & Comfort PlatesBtn'  or @accessibilityLabel='Cheesy & Comfort PlatesBtn'  or @label='Cheesy & Comfort PlatesBtn'  or @name='Cheesy & Comfort PlatesBtn'  or @accessibilityIdentifier='Cheesy & Comfort PlatesBtn'  or @content-desc='Cheesy & Comfort PlatesBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='ParmesanCrustedPotatoesItem'  or @accessibilityLabel='ParmesanCrustedPotatoesItem'  or @name='ParmesanCrustedPotatoesItem'  or @label='ParmesanCrustedPotatoesItem'  or @content-desc='ParmesanCrustedPotatoesItem'] ").click()
        self.driver.find_element_by_xpath("//*[@value='AddParmesanCrustBtn'  or @accessibilityLabel='AddParmesanCrustBtn'  or @label='AddParmesanCrustBtn'  or @name='AddParmesanCrustBtn'  or @accessibilityIdentifier='AddParmesanCrustBtn'  or @content-desc='AddParmesanCrustBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@value='Cheesy & Comfort PlatesBtn'  or @accessibilityLabel='Cheesy & Comfort PlatesBtn'  or @label='Cheesy & Comfort PlatesBtn'  or @name='Cheesy & Comfort PlatesBtn'  or @accessibilityIdentifier='Cheesy & Comfort PlatesBtn'  or @content-desc='Cheesy & Comfort PlatesBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='ParmesanCrustedPotatoesItem'  or @accessibilityLabel='ParmesanCrustedPotatoesItem'  or @name='ParmesanCrustedPotatoesItem'  or @label='ParmesanCrustedPotatoesItem'  or @content-desc='ParmesanCrustedPotatoesItem'] ").click()
        self.driver.find_element_by_xpath("(//*[@value='addNewCustomSelection'   or @name='addNewCustomSelection'   or @label='addNewCustomSelection'   or @accessibilityLabel='addNewCustomSelection'])[1] ").click()
        self.driver.find_element_by_xpath("//*[@value='AddSpicyDipBtn'  or @accessibilityLabel='AddSpicyDipBtn'  or @label='AddSpicyDipBtn'  or @name='AddSpicyDipBtn'  or @accessibilityIdentifier='AddSpicyDipBtn'  or @content-desc='AddSpicyDipBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='StartersBtn'  or @accessibilityLabel='StartersBtn'  or @label='StartersBtn'  or @name='StartersBtn'  or @accessibilityIdentifier='StartersBtn'  or @content-desc='StartersBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='VegManchurianItem'  or @accessibilityLabel='VegManchurianItem'  or @name='VegManchurianItem'  or @label='VegManchurianItem'  or @content-desc='VegManchurianItem'] ").click()
        self.driver.find_element_by_xpath("//*[@value='extrasauceBtn'  or @accessibilityLabel='extrasauceBtn'  or @label='extrasauceBtn'  or @name='extrasauceBtn'  or @accessibilityIdentifier='extrasauceBtn'  or @content-desc='extrasauceBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='assignToBtn' or @name='assignToBtn' or @label='assignToBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='assignToBtn' or @name='assignToBtn' or @label='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAll' or @name='selectAll' or @label='selectAll'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItem//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn'//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn'] ] sBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='sendItemsBtn' or @label='sendItemsBtn' or @accessibilityLabel='sendItemsBtn' or @text='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='backButton' or @name='backButton' or @label='backButton']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='backButton' or @name='backButton' or @label='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Menu' or @label='Menu' or @accessibilityLabel='Menu' or @text='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='logOutBtn' or @name='logOutBtn' or @label='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='emailValue' or @name='emailValue' or @label='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='passwordValue' or @name='passwordValue' or @label='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='clickCheckBox' or @name='clickCheckBox' or @label='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='signInBtn' or @name='signInBtn' or @label='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='inProgressOrderCard' or @name='inProgressOrderCard' or @label='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inProgressOrderCard' or @name='inProgressOrderCard' or @label='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@value='TagliatellealMonti2Freshchampignons TagliatellealMonti'  or @accessibilityLabel='TagliatellealMonti2Freshchampignons TagliatellealMonti'  or @label='TagliatellealMonti2Freshchampignons TagliatellealMonti'  or @name='TagliatellealMonti2Freshchampignons TagliatellealMonti'  or @accessibilityIdentifier='TagliatellealMonti2Freshchampignons TagliatellealMonti'  or @content-desc='TagliatellealMonti2Freshchampignons TagliatellealMonti'] ").click()
        self.driver.find_element_by_xpath("//*[@value='TagliatellealMonti2Cookedham TagliatellealMonti']").click()
        self.driver.find_element_by_xpath("//*[@value='ParmesanCrustedPotatoes2AddSpicyDip ParmesanCrustedPotatoes']").click()
        self.driver.find_element_by_xpath("//*[@value='VegManchurian2extrasauce VegManchurian']").click()
        self.driver.find_element_by_xpath("//*[@value='ParmesanCrustedPotatoes2AddParmesanCrust ParmesanCrustedPotatoes']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderReadyBtn' or @name='orderReadyBtn' or @label='orderReadyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderCloseBtn' or @name='orderCloseBtn' or @label='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Menu' or @label='Menu' or @accessibilityLabel='Menu' or @text='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='logOutBtn' or @name='logOutBtn' or @label='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='emailValue' or @name='emailValue' or @label='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='passwordValue' or @name='passwordValue' or @label='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='clickCheckBox' or @name='clickCheckBox' or @label='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='signInBtn' or @name='signInBtn' or @label='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Orders' or @name='Orders' or @label='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='ServeOrderCard' or @name='ServeOrderCard' or @label='ServeOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='serveItemsBtn' or @name='serveItemsBtn' or @label='serveItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='addItemsBtn' or @name='addItemsBtn' or @label='addItemsBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@value='Pasta & PizzaBtn' or @label='Pasta & PizzaBtn' or @name='Pasta & PizzaBtn']")))
        self.driver.find_element_by_xpath("//*[@value='StartersBtn'  or @accessibilityLabel='StartersBtn'  or @label='StartersBtn'  or @name='StartersBtn'  or @accessibilityIdentifier='StartersBtn'  or @content-desc='StartersBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='VegManchurianItem'  or @accessibilityLabel='VegManchurianItem'  or @name='VegManchurianItem'  or @label='VegManchurianItem'  or @content-desc='VegManchurianItem'] ").click()
        self.driver.find_element_by_xpath("//*[@value='extrasauceBtn'  or @accessibilityLabel='extrasauceBtn'  or @label='extrasauceBtn'  or @name='extrasauceBtn'  or @accessibilityIdentifier='extrasauceBtn'  or @content-desc='extrasauceBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='applyOptionBtn']").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='assignToBtn' or @name='assignToBtn' or @label='assignToBtn']")))
        self.driver.find_element_by_xpath("//*[@value='assignToBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAll' or @name='selectAll' or @label='selectAll'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@value='assignProductsBtns']").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='sendItemsBtn' or @label='sendItemsBtn' or @accessibilityLabel='sendItemsBtn' or @text='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='backButton' or @name='backButton' or @label='backButton']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='backButton' or @name='backButton' or @label='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Menu' or @label='Menu' or @accessibilityLabel='Menu' or @text='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='logOutBtn' or @name='logOutBtn' or @label='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='emailValue' or @name='emailValue' or @label='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='passwordValue' or @name='passwordValue' or @label='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='clickCheckBox' or @name='clickCheckBox' or @label='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='signInBtn' or @name='signInBtn' or @label='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='inProgressOrderCard' or @name='inProgressOrderCard' or @label='inProgressOrderCard']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inProgressOrderCard' or @name='inProgressOrderCard' or @label='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@value='VegManchurian1extrasauce VegManchurian']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderReadyBtn' or @name='orderReadyBtn' or @label='orderReadyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderCloseBtn' or @name='orderCloseBtn' or @label='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Menu' or @label='Menu' or @accessibilityLabel='Menu' or @text='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='logOutBtn' or @name='logOutBtn' or @label='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='emailValue' or @name='emailValue' or @label='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='passwordValue' or @name='passwordValue' or @label='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='clickCheckBox' or @name='clickCheckBox' or @label='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='signInBtn' or @name='signInBtn' or @label='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Orders' or @name='Orders' or @label='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='ServeOrderCard' or @name='ServeOrderCard' or @label='ServeOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='serveItemsBtn' or @name='serveItemsBtn' or @label='serveItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='notifyPaymentBtn' or @name='notifyPaymentBtn' or @label='notifyPaymentBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Payment Payment' or @label='Payment Payment' or @value='Payment Payment'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='RoopaDCard' or @name='RoopaDCard' or @label='RoopaDCard'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='cashPaymentBtn' or @name='cashPaymentBtn' or @label='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Number1' or @name='Number1' or @label='Number1'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Number4' or @name='Number4' or @label='Number4'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Number0' or @name='Number0' or @label='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='userInputBtn' or @name='userInputBtn' or @label='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Guest1select' or @label='Guest1select' or @accessibilityLabel='Guest1select'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Apply' or @label='Apply' or @accessibilityLabel='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='paymentConfirmBtn' or @name='paymentConfirmBtn' or @label='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='paymentConfirmBtn' or @name='paymentConfirmBtn' or @label='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='RoopaDCard' or @name='RoopaDCard' or @label='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@text='Overview Overview' or @label='Overview Overview' or @name='Overview Overview' or @value='Overview Overview'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@value='closeTableBtn' or @name='closeTableBtn' or @label='closeTableBtn' or @content-desc='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@value='closeTableBtn' or @name='closeTableBtn' or @label='closeTableBtn' or @content-desc='closeTableBtn'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        self.driver.execute_script("seetest:client.sendText(\"2. Book an Event with Guest for 3 hours\")")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@name='NylaiKitchen' or @label='NylaiKitchen' or @accessibilityLabel='NylaiKitchen']")))
        self.driver.swipe(690, 1654, 654, 1433, 313)
        self.driver.find_element_by_xpath("//*[@name='NylaiKitchen' or @label='NylaiKitchen' or @accessibilityLabel='NylaiKitchen'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Any']')))
        self.driver.find_element_by_xpath("//*[@content-desc='counterPlus']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='guestAdd']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='inviteUsers']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='3 hrs' or @name='3 hrs' or @label='3 hrs'] ").click()
        self.driver.find_element_by_xpath("xpath=//*[@accessibilityLabel='chip-container'] ").click()
        self.driver.find_element_by_xpath("//*[@name='bookAppoitment' or @label='bookAppoitment'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@name='Allow' or @label='Allow']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Orders' or @name='Orders' or @label='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='ReservedOrderCard' or @name='ReservedOrderCard' or @label='ReservedOrderCard'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='T19AssignAnyBtn' or @name='T19AssignAnyBtn' or @label='T19AssignAnyBtn']")))
        self.driver.find_element_by_xpath("//*[@value='T0AssignAnyBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='AssignTableBtn' or @name='AssignTableBtn' or @label='AssignTableBtn'] ").click()
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyaconsumer", "")
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='addItemsBtn' or @name='addItemsBtn' or @label='addItemsBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='walletTab' or @name='walletTab' or @label='walletTab' or @accessibilityIdentifier='walletTab' or @content-desc='walletTab'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='NylaiKitchenCard' or @name='NylaiKitchenCard' or @label='NylaiKitchenCard' or @accessibilityIdentifier='NylaiKitchenCard' or @content-desc='NylaiKitchenCard' or @value='NylaiKitchenCard'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='TomYumSoupInc' or @name='TomYumSoupInc' or @label='TomYumSoupInc' or @accessibilityIdentifier='TomYumSoupInc' or @content-desc='TomYumSoupInc' or @value='TomYumSoupInc']")))
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='TomYumSoupInc' or @name='TomYumSoupInc' or @label='TomYumSoupInc' or @accessibilityIdentifier='TomYumSoupInc' or @content-desc='TomYumSoupInc' or @value='TomYumSoupInc'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='prawnProduct' or @name='prawnProduct' or @label='prawnProduct' or @accessibilityIdentifier='prawnProduct' or @content-desc='prawnProduct' or @value='prawnProduct'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='confirmProduct' or @name='confirmProduct' or @label='confirmProduct' or @accessibilityIdentifier='confirmProduct' or @content-desc='confirmProduct' or @value='confirmProduct'] ").click()
        self.driver.find_element_by_xpath("(//*[@accessibilityLabel='cheesy-comfort-platescategory'   or @name='cheesy-comfort-platescategory'   or @label='cheesy-comfort-platescategory'   or @value='cheesy-comfort-platescategory'])[1] ").click()
        self.driver.find_element_by_xpath("(//*[@accessibilityLabel='FourCheeseLasagna'   or @name='FourCheeseLasagna'   or @label='FourCheeseLasagna'   or @value='FourCheeseLasagna'])[1] ").click()
        self.driver.find_element_by_xpath("(//*[@accessibilityLabel='AddMushroomProduct'   or @name='AddMushroomProduct'   or @label='AddMushroomProduct'   or @value='AddMushroomProduct'])[1] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='confirmProduct' or @name='confirmProduct' or @label='confirmProduct' or @accessibilityIdentifier='confirmProduct' or @content-desc='confirmProduct' or @value='confirmProduct'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='cartImage' or @name='cartImage' or @label='cartImage' or @accessibilityIdentifier='cartImage' or @content-desc='cartImage' or @value='cartImage'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='CONFIRM ORDER' or @name='CONFIRM ORDER' or @label='CONFIRM ORDER' or @accessibilityIdentifier='CONFIRM ORDER' or @content-desc='CONFIRM ORDER' or @value='CONFIRM ORDER'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderConfirmedMenu' or @name='orderConfirmedMenu' or @label='orderConfirmedMenu' or @accessibilityIdentifier='orderConfirmedMenu' or @content-desc='orderConfirmedMenu' or @value='orderConfirmedMenu'] ").click()
        self.driver.swipe(563, 2260, 618, 1121, 169)
        self.driver.press_keycode(3) # home
        self.driver.startActivity("org.vyapy.sarls.vyabusinessipad", "")
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@name='Allow' or @label='Allow']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Orders' or @name='Orders' or @label='Orders'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,''OrderOrderCard'   or @name='OrderOrderCard'   or @label='OrderOrderCard'   or @value='OrderOrderCard'])[1]')))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='OrderOrderCard']").click()
        self.driver.find_element_by_xpath("(//*[@value='Backbtn'   or @name='Backbtn'   or @label='Backbtn'   or @accessibilityLabel='Backbtn'])[1] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='OrderOrderCard']").click()
        self.driver.find_element_by_xpath("(//*[@value='addItemsBtn'   or @name='addItemsBtn'   or @label='addItemsBtn'   or @accessibilityLabel='addItemsBtn'])[1] ").click()
        self.driver.find_element_by_xpath("//*[@value='Chicken65Item'  or @accessibilityLabel='Chicken65Item'  or @name='Chicken65Item'  or @label='Chicken65Item'  or @content-desc='Chicken65Item'] ").click()
        self.driver.find_element_by_xpath("//*[@value='addmayoBtn'  or @accessibilityLabel='addmayoBtn'  or @label='addmayoBtn'  or @name='addmayoBtn'  or @accessibilityIdentifier='addmayoBtn'  or @content-desc='addmayoBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='Pasta & PizzaBtn'  or @accessibilityLabel='Pasta & PizzaBtn'  or @label='Pasta & PizzaBtn'  or @name='Pasta & PizzaBtn'  or @accessibilityIdentifier='Pasta & PizzaBtn'  or @content-desc='Pasta & PizzaBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@value='TagliatellealMontiItem'  or @accessibilityLabel='TagliatellealMontiItem'  or @name='TagliatellealMontiItem'  or @label='TagliatellealMontiItem'  or @content-desc='TagliatellealMontiItem'] ").click()
        self.driver.find_element_by_xpath("//*[@value='CookedhamBtn'  or @accessibilityLabel='CookedhamBtn'  or @label='CookedhamBtn'  or @name='CookedhamBtn'  or @accessibilityIdentifier='CookedhamBtn'  or @content-desc='CookedhamBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='applyOptionBtn' or @name='applyOptionBtn' or @label='applyOptionBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='assignToBtn' or @name='assignToBtn' or @label='assignToBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAll' or @name='selectAll' or @label='selectAll'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItem//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn'//*[@accessibilityLabel='assignProductsBtn' or @name='assignProductsBtn' or @label='assignProductsBtn'] ] sBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='sendItemsBtn' or @label='sendItemsBtn' or @accessibilityLabel='sendItemsBtn' or @text='sendItemsBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='backButton' or @name='backButton' or @label='backButton']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='backButton' or @name='backButton' or @label='backButton'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Menu' or @label='Menu' or @accessibilityLabel='Menu' or @text='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='logOutBtn' or @name='logOutBtn' or @label='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='emailValue' or @name='emailValue' or @label='emailValue'] ").send_keys('kempA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='passwordValue' or @name='passwordValue' or @label='passwordValue'] ").send_keys('Nylaii@09')
        self.driver.hide_keyboard()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='clickCheckBox' or @name='clickCheckBox' or @label='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='signInBtn' or @name='signInBtn' or @label='signInBtn'] ").click()
        WebDriverWait(self.driver, 3).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='inProgressOrderCard' or @name='inProgressOrderCard' or @label='inProgressOrderCard']")))
        self.driver.hide_keyboard()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='inProgressOrderCard' or @name='inProgressOrderCard' or @label='inProgressOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@value='TomYumSoup1vegchickenprawn TomYumSoup']").click()
        self.driver.find_element_by_xpath("//*[@value='FourCheeseLasagna1AddMushroom FourCheeseLasagna']").click()
        self.driver.find_element_by_xpath("//*[@value='Chicken652addmayo Chicken65']").click()
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@value='TagliatellealMonti2Cookedham TagliatellealMonti']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderReadyBtn' or @name='orderReadyBtn' or @label='orderReadyBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='orderCloseBtn' or @name='orderCloseBtn' or @label='orderCloseBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Menu' or @label='Menu' or @accessibilityLabel='Menu' or @text='Menu'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='logOutBtn' or @name='logOutBtn' or @label='logOutBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='emailValue' or @name='emailValue' or @label='emailValue'] ").send_keys('empA@xorstack.com')
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='passwordValue' or @name='passwordValue' or @label='passwordValue'] ").send_keys('Nylaii@06')
        self.driver.swipe(776, 1817, 770, 1220, 198)
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='clickCheckBox' or @name='clickCheckBox' or @label='clickCheckBox'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='signInBtn' or @name='signInBtn' or @label='signInBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Orders' or @name='Orders' or @label='Orders'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='ServeOrderCard' or @name='ServeOrderCard' or @label='ServeOrderCard'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='selectAllItemsBtn' or @name='selectAllItemsBtn' or @label='selectAllItemsBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='serveItemsBtn' or @name='serveItemsBtn' or @label='serveItemsBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='notifyPaymentBtn' or @name='notifyPaymentBtn' or @label='notifyPaymentBtn'] ").click()
        WebDriverWait(self.driver, 4).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@name='Payment Payment' or @label='Payment Payment' or @value='Payment Payment']")))
        self.driver.find_element_by_xpath("//*[@name='Payment Payment' or @label='Payment Payment' or @value='Payment Payment'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='RoopaDCard' or @name='RoopaDCard' or @label='RoopaDCard'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='cashPaymentBtn' or @name='cashPaymentBtn' or @label='cashPaymentBtn']").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Number4' or @name='Number4' or @label='Number4] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Number0' or @name='Number0' or @label='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='Number0' or @name='Number0' or @label='Number0'] ").click()
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='userInputBtn' or @name='userInputBtn' or @label='userInputBtn'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Guest1select' or @label='Guest1select' or @accessibilityLabel='Guest1select'] ").click()
        self.driver.find_element_by_xpath("//*[@name='Apply' or @label='Apply' or @accessibilityLabel='Apply'] ").click()
        self.driver.swipe(520, 1662, 537, 1086, 224)
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='paymentConfirmBtn' or @name='paymentConfirmBtn' or @label='paymentConfirmBtn']")))
        self.driver.find_element_by_xpath("//*[@accessibilityLabel='paymentConfirmBtn' or @name='paymentConfirmBtn' or @label='paymentConfirmBtn'] ").click()
        WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@accessibilityLabel='RoopaDCard' or @name='RoopaDCard' or @label='RoopaDCard']")))
        self.driver.find_element_by_xpath("//*[@text='Overview Overview' or @label='Overview Overview' or @name='Overview Overview' or @value='Overview Overview'] ").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[@value='closeTableBtn' or @name='closeTableBtn' or @label='closeTableBtn' or @content-desc='closeTableBtn']")))
        self.driver.find_element_by_xpath("//*[@value='closeTableBtn' or @name='closeTableBtn' or @label='closeTableBtn' or @content-desc='closeTableBtn'] ").click()
        self.driver.press_keycode(3) # home

    def tearDown(self):
        self.driver.quit()
        
    if __name__ == '__main__':
        unittest.main()
